name: Release

on:
  workflow_dispatch:
    inputs:
      publish:
        description: 'Create release for:'
        required: true
        default: DigitalBattleMap
        type: choice
        options:
          - DigitalBattleMap
          - DigitalBattleMapServer
          - DigitalBattleMap_DigitalBattleMapServer

jobs:
  Build:
    runs-on: windows-latest

    # steps:
    # - name: Checkout
    #   uses: actions/checkout@v3
    #   with:
    #     fetch-depth: 0

    # - name: Install .NET Core
    #   uses: actions/setup-dotnet@v3
    #   with:
    #     dotnet-version: 6.0.x

    # # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    # - name: Setup MSBuild.exe
    #   uses: microsoft/setup-msbuild@v1.0.2

    # - name: Setup Python 3.10
    #   uses: actions/setup-python@v3
    #   with:
    #     python-version: '3.10'

    # - name: Build All
    #   run: py Scripts/BuildAll.py

    # - name: Run tests
    #   run: py Scripts/TestAll.py
